services:
  db:
    container_name: "Gestion-de-Pedidos"
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "GestionPedidos"
      POSTGRES_USER: "grupo2"
      POSTGRES_PASSWORD: "secret$"
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app-network

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_SERVER_ID: 1
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "zkServer.sh", "status" ]

  kafka:
    image: bitnami/kafka:3.6.2
    container_name: kafka
    hostname: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge